.section .data
string_for_0:
    .string "called 0\n"

string_for_1:
    .string "called 1\n"

string_for_2:
    .string "called 2\n"

string_for_3:
    .string "called 3\n"

string_for_4:
    .string "called 4\n"

string_for_5:
    .string "called 5\n"

string_for_6:
    .string "called 6\n"

string_for_7:
    .string "called 7\n"

string_for_8:
    .string "called 8\n"

string_for_9:
    .string "called 9\n"

string_for_10:
    .string "called 10\n"

string_for_11:
    .string "called 11\n"

string_for_12:
    .string "called 12\n"

string_for_13:
    .string "called 13\n"

string_for_14:
    .string "called 14\n"

string_for_15:
    .string "called 15\n"

string_for_16:
    .string "called 16\n"

string_for_17:
    .string "called 17\n"

string_for_18:
    .string "called 18\n"

string_for_19:
    .string "called 19\n"

string_for_20:
    .string "called 20\n"

string_for_21:
    .string "called 21\n"

string_for_22:
    .string "called 22\n"

string_for_23:
    .string "called 23\n"

string_for_24:
    .string "called 24\n"

string_for_25:
    .string "called 25\n"

string_for_26:
    .string "called 26\n"

string_for_27:
    .string "called 27\n"

string_for_28:
    .string "called 28\n"

string_for_29:
    .string "called 29\n"

string_for_30:
    .string "called 30\n"

string_for_31:
    .string "called 31\n"


.section .text
.global isr0
.type isr0, @function
isr0:
    push $string_for_0
    call printf
    iretl
.size isr0, . - isr0

.global isr1
.type isr1, @function
isr1:
    push $string_for_1
    call printf
    iretl
.size isr1, . - isr1

.global isr2
.type isr2, @function
isr2:
    push $string_for_2
    call printf
    iretl
.size isr2, . - isr2

.global isr3
.type isr3, @function
isr3:
    push $string_for_3
    call printf
    iretl
.size isr3, . - isr3

.global isr4
.type isr4, @function
isr4:
    push $string_for_4
    call printf
    iretl
.size isr4, . - isr4

.global isr5
.type isr5, @function
isr5:
    push $string_for_5
    call printf
    iretl
.size isr5, . - isr5

.global isr6
.type isr6, @function
isr6:
    push $string_for_6
    call printf
    iretl
.size isr6, . - isr6

.global isr7
.type isr7, @function
isr7:
    push $string_for_7
    call printf
    iretl
.size isr7, . - isr7

.global isr8
.type isr8, @function
isr8:
    push $string_for_8
    call printf
    iretl
.size isr8, . - isr8

.global isr9
.type isr9, @function
isr9:
    push $string_for_9
    call printf
    iretl
.size isr9, . - isr9

.global isr10
.type isr10, @function
isr10:
    push $string_for_10
    call printf
    iretl
.size isr10, . - isr10

.global isr11
.type isr11, @function
isr11:
    push $string_for_11
    call printf
    iretl
.size isr11, . - isr11

.global isr12
.type isr12, @function
isr12:
    push $string_for_12
    call printf
    iretl
.size isr12, . - isr12

.global isr13
.type isr13, @function
isr13:
    push $string_for_13
    call printf
    iretl
.size isr13, . - isr13

.global isr14
.type isr14, @function
isr14:
    push $string_for_14
    call printf
    iretl
.size isr14, . - isr14

.global isr15
.type isr15, @function
isr15:
    push $string_for_15
    call printf
    iretl
.size isr15, . - isr15

.global isr16
.type isr16, @function
isr16:
    push $string_for_16
    call printf
    iretl
.size isr16, . - isr16

.global isr17
.type isr17, @function
isr17:
    push $string_for_17
    call printf
    iretl
.size isr17, . - isr17

.global isr18
.type isr18, @function
isr18:
    push $string_for_18
    call printf
    iretl
.size isr18, . - isr18

.global isr19
.type isr19, @function
isr19:
    push $string_for_19
    call printf
    iretl
.size isr19, . - isr19

.global isr20
.type isr20, @function
isr20:
    push $string_for_20
    call printf
    iretl
.size isr20, . - isr20

.global isr21
.type isr21, @function
isr21:
    push $string_for_21
    call printf
    iretl
.size isr21, . - isr21

.global isr22
.type isr22, @function
isr22:
    push $string_for_22
    call printf
    iretl
.size isr22, . - isr22

.global isr23
.type isr23, @function
isr23:
    push $string_for_23
    call printf
    iretl
.size isr23, . - isr23

.global isr24
.type isr24, @function
isr24:
    push $string_for_24
    call printf
    iretl
.size isr24, . - isr24

.global isr25
.type isr25, @function
isr25:
    push $string_for_25
    call printf
    iretl
.size isr25, . - isr25

.global isr26
.type isr26, @function
isr26:
    push $string_for_26
    call printf
    iretl
.size isr26, . - isr26

.global isr27
.type isr27, @function
isr27:
    push $string_for_27
    call printf
    iretl
.size isr27, . - isr27

.global isr28
.type isr28, @function
isr28:
    push $string_for_28
    call printf
    iretl
.size isr28, . - isr28

.global isr29
.type isr29, @function
isr29:
    push $string_for_29
    call printf
    iretl
.size isr29, . - isr29

.global isr30
.type isr30, @function
isr30:
    push $string_for_30
    call printf
    iretl
.size isr30, . - isr30

.global isr31
.type isr31, @function
isr31:
    push $string_for_31
    call printf
    iretl
.size isr31, . - isr31

